language: java
jdk:
        - openjdk11
branches:
        only:
                - main

# Travis cI 서버의 HOME
cache:
        directories:
                - '$HOME/.m2/repository'
                - '$HOME/.gradle'

# main브랜치에 푸시되었을 때 수행할 명령어                  
script: "./gradlew clean build"

# CI 실행완료 시 메일로 알람
notifications:
        email:
                recipients:
                        - mhong0800@gmail.com


before_deploy:
        - zip -r 42BoB-s_solution 
        - mkdir -p deploy
        - mv 42BoB-s_solution.zip deploy/42BoB-s_solution.zip

deploy:
        - provider: s3
          access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
          secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
          bucket: 42bobs-build # S3 버킷i
          region: ap-northeast-2
          skip_cleanup: true
          acl: private #zip 파일 접근을 private으로
          local_dir: deploy # before_deploy에서 생성한 디렉토리
          wait_until_deployed: true
          on:
                branches:
                        only:
                                - main

