language: java
jdk:
        - openjdk11
branches:
        only:
                - main

# Travis cI 서버의 HOME
cache:
        directories:
                - '$HOME/.m2/repository'
                - '$HOME/.gradle'

# main브랜치에 푸시되었을 때 수행할 명령어                  
script: "./gradlew clean build"

# CI 실행완료 시 메일로 알람
notifications:
        email:
                recipients:
                        - mhong0800@gmail.com

